# Runs all of the tests available
name: Test

# Run the workflow on push to and pull request from any branch, and when manually triggered
on: [push, pull_request, workflow_dispatch]

jobs:
  # Setup the environment and then run tests
  runTests:
    # Run tests on a ubuntu machine
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo onto the runner
      - name: Checkout
        uses: actions/checkout@v3
        
      # Install node
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: '17.5.0'
          
      # Install dependencies (note that during CI "npm ci" needs to be used instead of "npm i")
      - name: Install repo dependencies
        run: npm ci
        
      # Build the project
      - name: Build project
        run: npm run build
      
      # Run all tests
      - name: Run all tests
        run: npm run test
  
  # Run Cypress e2e tests
  runE2eTests:
    runs-on: ubuntu-latest

    steps:
      # Checkout the backend repo onto the runner
      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          repository: kyfohatl/portfolio-website-backend
      
      - name: Check if it worked
        run: ls -a